spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/orders_db
    username: postgres
    password: orderspass
  jpa:
    hibernate:
      ddl-auto: update # week 1 only
    show-sql: true
    properties:
      hibernate:
        format_sql: true